name: Latte lint (PHP)

on: [ push, pull_request ]

jobs:
  test:
    name: Latte with PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ./.github/setup

      - run: composer run-script latteLint
        name: Test