name: Latte lint (PHP)

on: [ push, pull_request ]

jobs:
  test:
    name: Latte with PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1' ]
    steps:
      - uses: ./.github.actions/setup.yml

      - run: composer run-script latteLint
        name: Test
      - if: failure()
        name: Failure output
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: tests/**/*.actual
